const projectData = [
  {
    title: "UnifyOps - Internal Developer Platform",
    img: "/docker.svg",
    role: "Platform Engineering",
    desc: "An internal developer platform I designed and operate end-to-end. Deploys multi-service systems safely using GitOps, Kubernetes, and strict runtime isolation. Three-tier stack architecture with enforced network boundaries, zero-downtime deploys, and a shared core package for consistent logging, auth, and error handling.",
    outcome: "Zero-downtime deploys with ordered migrations, strict network isolation, GitOps rollback via image tag revert.",
    url: "/projects/unifyops",
    badge: "DEEP DIVE",
    target: "_self",
  },
  {
    title: "Job Scanner - LLM Automation",
    img: "/openai.svg",
    role: "Automation",
    desc: "Automated job screening pipeline leveraging LLM-based evaluation with GPT-4. Scrapes LinkedIn listings via Playwright, scores role fit against user profiles, and applies deterministic gates for dealbreakers. Generates tailored cover letters and recruiter outreach messages for high-match roles. Features full audit trail with prompt versioning, regression testing, and structured output validation.",
    outcome: "Automates 80% of job screening workflow with structured LLM evaluation.",
    url: "https://github.com/KominskyOrg/job-scanner",
    badge: "NEW",
  },
  {
    title: "Python Core Package",
    img: "/python-logo.svg",
    role: "Platform Engineering",
    desc: "Foundational Python library providing standardized utilities across all organization microservices. Includes HTTPClient for service-to-service communication with timeout and error handling, LoggingConfig with JSON formatting and rotating file handlers, and typed API exceptions (ValidationError, AuthenticationError, DatabaseError). Published to self-hosted Harbor registry on bare-metal Kubernetes infrastructure.",
    outcome: "Eliminates boilerplate across microservices with standardized logging and error handling.",
    url: "https://github.com/KominskyOrg/kom_python_core",
    badge: "NEW",
  },
  {
    title: "Home Infrastructure",
    img: "/EKS Cloud.svg",
    role: "Site Reliability",
    desc: "Modular Terraform infrastructure managing VPC, Kubernetes (EKS), and RDS resources with multi-environment support (dev/staging/prod). Features GitOps CI/CD workflows, S3/DynamoDB state management, ALB Ingress Controller, and ACM certificate automation. Deployed to bare-metal Kubernetes on home server infrastructure.",
    outcome: "Provides repeatable multi-environment deployments with disaster recovery under 30 minutes.",
    url: "https://github.com/KominskyOrg/kom_aws_tf",
  },
  {
    title: "Kominsky Terraform Modules",
    img: "/terraform.svg",
    role: "Platform Engineering",
    desc: "Reusable Terraform modules for Kubernetes and database infrastructure. EKS module provides configurable Kubernetes Deployments with health probes, dynamic environment variables, and node selectors. DB module integrates AWS Secrets Manager with Kubernetes secrets and Lambda-based database provisioning. Consumed via Git refs for versioned, consistent infrastructure patterns.",
    outcome: "Standardizes Kubernetes deployments across services with consistent health checks and scaling.",
    url: "https://github.com/KominskyOrg/kom-tf-modules",
  },
  {
    title: "Stack Templates",
    img: "/github-mark.svg",
    role: "Platform Engineering",
    desc: "Production-ready microservice architecture templates implementing a three-tier pattern (App → API Gateway → Service). Each template includes Flask/React foundations, multi-environment Dockerfiles, and Terraform for Kubernetes deployment. Docker images and Helm charts publish to self-hosted Harbor registry with pre-configured GitHub Actions CI/CD. Replace 'stack' placeholder with your service name for rapid microservice scaffolding.",
    outcome: "Reduces new microservice setup from days to under an hour.",
    url: "https://github.com/orgs/KominskyOrg/repositories?q=template",
    badge: "NEW",
  },
  {
    title: "Automated Repo Creation",
    img: "/github-mark.svg",
    role: "Automation",
    desc: "Infrastructure-as-Code tool for GitHub repository management. Converts JSON configuration files into Terraform resources for github_repository, github_branch_protection, and github_branch_default. Enforces consistent branch protection rules, merge strategies, and code owner requirements across 18+ organization repositories.",
    outcome: "Enforces security and CI standards across 18+ repositories without manual review.",
    url: "https://github.com/KominskyOrg/repo-creation",
  },
  {
    title: "Kominsky Auth Platform",
    img: "/github-mark.svg",
    role: "Site Reliability",
    desc: "Production-ready authentication platform built with microservices architecture. React/TypeScript frontend communicates through a Flask API Gateway to backend services with SQLAlchemy and Alembic migrations. Docker images and Helm charts published to self-hosted Harbor registry, deployed to bare-metal Kubernetes with automated CI/CD using reusable GitHub Actions workflows. Features JWT authentication, token refresh, password reset, and account management.",
    outcome: "Demonstrates full microservices lifecycle from development to production Kubernetes.",
    url: "https://github.com/orgs/KominskyOrg/repositories?q=auth",
    badge: "NEW",
  },
  {
    title: "Kominsky Portfolio",
    img: "/github-mark.svg",
    role: "Automation",
    desc: "My CV/Portfolio website, powered by Astro, serves as an interactive hub, presenting my career highlights, project links, and contact information, encapsulating my professional narrative in a sleek, minimalistic, user-friendly format.",
    outcome: "Showcases DevOps practices with automated deployment via GitHub Actions and CloudFront.",
    url: "https://github.com/KominskyOrg/kom-portfolio",
  },
];

export default projectData;
